### PR TITLE
Android RTS Support

### PR DESCRIPTION
**Pull request by chrisdack**
Added RTS support option to support the monkeyboard DAB development board.

[http://www.monkeyboard.org/products/85-developmentboard/85-dab-dab-fm-digital-radio-development-board-pro](http://www.monkeyboard.org/products/85-developmentboard/85-dab-dab-fm-digital-radio-development-board-pro)

This can be enabled just like DTR:
` serial.requestPermission({
            vid: '04D8',
            pid: '000A',
            dtr: false,
            rts: true,
            driver: 'CdcAcmSerialDriver' // or any other
        }function(successMessage) {
})`

### CODE REVIEW

**Comment by xseignard** [comment]
Hello @chrisdack thanks for the PR! It is very welcome.
Could you please update the readme too?

Regards

**Comment by chrisdack** [comment]
Thanks @xseignard, I've updated the readme as requested.

**Comment by xseignard** [comment]
Great! Merging it asap, and releasing a new version on npm.

Thanks and regards!

**Comment by xseignard** [comment]
Done

**Pull request merged**
